version: '3.8'

services:
  server:
    container_name: server
    image: tictactwo-server
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "3005:3005"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:3005
      - ConnectionStrings__DefaultConnection=postgresql://postgres:postgres@tictactwo-database-jmvncl:5432/tictactwo
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3005/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "3004:80"
    depends_on:
      - server