services:
    server:
        container_name: server
        image: tictactwo-server
        build:
            context: .
            dockerfile: Dockerfile.server
        ports:
            - "3005:3005"
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=http://+:3005
            - ConnectionStrings__DefaultConnection=Host=db;Database=tic_tac_two;Username=postgres;Password=PGtitan4321
        depends_on:
            db:
                condition: service_healthy
        restart: on-failure
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:3005/health"]
            interval: 30s
            timeout: 10s
            retries: 5
    
    client:
        build:
            context: .
            dockerfile: Dockerfile.client
        ports:
            - "3004:80"
        depends_on:
            - server
    
    db:
        image: postgres:15
        environment:
            POSTGRES_DB: tic_tac_two
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: PGtitan4321
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "1231:1231"
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U postgres" ]
            interval: 5s
            timeout: 5s
            retries: 5

volumes:
    postgres_data:
