FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /app

COPY TicTacTwo.sln ./
COPY Client/Client.csproj ./Client/
COPY Shared/Shared.csproj ./Shared/

RUN dotnet restore Client/Client.csproj
COPY . .
RUN dotnet publish Client/Client.csproj -c Release -o /out

FROM nginx:1.23.0-alpine
WORKDIR /app
EXPOSE 80
COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=build /out/wwwroot /usr/share/nginx/html