services:
    server:
        container_name: server
        image: tictactwo-server
        build:
            context: .
            dockerfile: Dockerfile.server
        ports:
            - "3005:3005"
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=http://+:3005
            - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=tic_tac_two;Username=postgres;Password=PGtitan4321
            - API_BASE_URL=http://localhost:3005
        depends_on:
            db:
                condition: service_healthy
        restart: on-failure
        healthcheck:
            test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3005/health" ]
            interval: 30s
            timeout: 10s
            retries: 5
    
    client:
        build:
            context: .
            dockerfile: Dockerfile.client
        ports:
            - "3004:80"
        depends_on:
            - server
        networks:
            - default
    
    db:
        image: postgres:15
        environment:
            POSTGRES_DB: tic_tac_two
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: PGtitan4321
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U postgres" ]
            interval: 5s
            timeout: 5s
            retries: 5
        networks:
            - default

volumes:
    postgres_data:

networks:
    default:
        name: tictactwo-network
        external: false
