// <auto-generated />
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("DAL.GameConfigurationDB", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("BoardSizeHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BoardSizeWidth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChipsCount")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MovableBoardHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MovableBoardWidth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OptionsAfterNMoves")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WinCondition")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("GameConfigurations");
                });

            modelBuilder.Entity("DAL.GameSessionDB", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("GameMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GamePassword")
                        .HasColumnType("TEXT");

                    b.Property<string>("GameStateId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Player1Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Player2Id")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameStateId");

                    b.HasIndex("Player1Id");

                    b.HasIndex("Player2Id");

                    b.ToTable("GameSessions");
                });

            modelBuilder.Entity("DAL.GameStateDB", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Board")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChipsLeft")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GameConfigId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GridX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GridY")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Player1Options")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Player2Options")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlayersMoves")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Win")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("GameStates");
                });

            modelBuilder.Entity("DAL.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DAL.GameSessionDB", b =>
                {
                    b.HasOne("DAL.GameStateDB", "GameState")
                        .WithMany()
                        .HasForeignKey("GameStateId");

                    b.HasOne("DAL.User", "Player1")
                        .WithMany()
                        .HasForeignKey("Player1Id");

                    b.HasOne("DAL.User", "Player2")
                        .WithMany()
                        .HasForeignKey("Player2Id");

                    b.Navigation("GameState");

                    b.Navigation("Player1");

                    b.Navigation("Player2");
                });
#pragma warning restore 612, 618
        }
    }
}
